#+TITLE: HyprLand Configuration (Org Mode)
#+DESCRIPTION: Here lies all the configuration for hyprland, made with Org Mode!
#+AUTHOR: Gu1Hyp3r
#+PROPERTY: header-args:conf :tangle hyprland.conf


* TABLE OF CONTENTS :toc:
- [[#about-this-config][ABOUT THIS CONFIG]]
  - [[#accept-custom-config-directory][Accept custom config directory]]
  - [[#needed-packages][Needed packages]]
- [[#monitors][MONITORS]]
  - [[#initialize-monitors][Initialize monitors]]
  - [[#initialize-workspaces][Initialize workspaces]]
- [[#my-programs][MY PROGRAMS]]
- [[#environment-variables][ENVIRONMENT VARIABLES]]
  - [[#cursor][Cursor]]
  - [[#primary-gpu-amd][Primary GPU (AMD)]]
  - [[#fonts][Fonts]]
  - [[#hardware-acceleration][Hardware acceleration]]
  - [[#tearing-control-optional][Tearing control (optional)]]
- [[#auto-start][AUTO START]]
  - [[#daemons][Daemon's]]
  - [[#packages][Packages]]
  - [[#nvidia-power-management][NVIDIA power management]]
  - [[#workspaces][Workspaces]]
- [[#look-and-feel][LOOK AND FEEL]]
- [[#input][INPUT]]
- [[#keybindings][KEYBINDINGS]]
  - [[#main][Main]]
  - [[#swww-change-random-wallpaper][SWWW change random wallpaper]]
  - [[#workspaces-1][Workspaces]]
  - [[#other][Other]]
- [[#windows-and-workspaces][WINDOWS AND WORKSPACES]]

* ABOUT THIS CONFIG
** Accept custom config directory
The hyprland config is set to be on a non default directory, so you need to setup a symlink to create a reference of the config to the default directory that hyperland accepts.
#+begin_src bash
  ln -s ~/.config/hypr/hyprland/hyprland.conf ~/.config/hypr/hyprland.conf

#+end_src

** Needed packages
*** Hypsrsome: https://github.com/sopa0/hyprsome
This package is responsible for controlling the workspaces in all monitors.

**** Installation guide
The default installation from github doesnt work (at least for now), but here is a working one:
#+begin_src bash
  git clone https://github.com/sopa0/hyprsome
  cd hyprsome
  cargo build --release
  sudo cp target/release/hyprsome /usr/local/bin

  # Just to free some space
  cd ..
  rm -rf hyprsome/

#+end_src

*** SWWW: https://github.com/LGFae/swww
This package is responsible for controlling wallpapers.

**** Installation guide
#+begin_src bash
  git clone https://github.com/LGFae/swww.git
  cd swww
  cargo build --release
  sudo cp ./target/release/swww /usr/local/bin/
  sudo cp ./target/release/swww-daemon /usr/local/bin

  # Just to free some space
  cd ..
  rm -rf swww/

#+end_src



* MONITORS
** Initialize monitors
#+begin_src conf
  $monitor1 = eDP-1
  $monitor2 = DP-6

  monitor = $monitor1, highrr, 0x0, 1.0
  monitor = $monitor2, highrr, -1920x0, 1.0

#+end_src

** Initialize workspaces
#+begin_src conf
  workspace = 1, monitor:$monitor1, persistent:true
  workspace = 2, monitor:$monitor1
  workspace = 3, monitor:$monitor1
  workspace = 4, monitor:$monitor1
  workspace = 5, monitor:$monitor1
  workspace = 6, monitor:$monitor1
  workspace = 7, monitor:$monitor1
  workspace = 8, monitor:$monitor1
  workspace = 9, monitor:$monitor1

  workspace = 11, monitor:$monitor2, persistent:true
  workspace = 12, monitor:$monitor2
  workspace = 13, monitor:$monitor2
  workspace = 14, monitor:$monitor2
  workspace = 15, monitor:$monitor2
  workspace = 16, monitor:$monitor2
  workspace = 17, monitor:$monitor2
  workspace = 18, monitor:$monitor2
  workspace = 19, monitor:$monitor2

#+end_src


* MY PROGRAMS
#+begin_src conf
  $terminal = kitty
  $fileManager = dolphin
  $menu = wofi --show drun

#+end_src


* ENVIRONMENT VARIABLES
** Cursor
#+begin_src conf
  env = XCURSOR_SIZE, 24
  env = HYPRCURSOR_SIZE, 24
  env = WLR_NO_HARDWARE_CURSORS, 1
  env = WLR_REDERER_ALLOW_SOFTWARE, 1

#+end_src

** Primary GPU (AMD)
#+begin_src conf
  env = WLR_DRM_DEVICES, /dev/dri/card0
  env = LIBVA_DRIVER_NAME, radeonsi
  env = GBM_BACKEND, nvidia-drm
  env = __GLX_VENDOR_LIBRARY_NAME, mesa
  env = WLR_DRM_NO_ATOMIC, 1
  env = __GL_MinimizeStalling, 0

#+end_src

** Fonts
#+begin_src conf
  env = GDK_THEME, Adwaita-dark
  env = GTK_FONT, CaskaydiaCove Nerd Font, 12
  env = GTK_MONOSPACE_FONT, Cascaydia Nerd Font Mono, 12
  env = QT_FONT, CaskaydiaCove Nerd Font 14
  env = GDK_SCALE, 1.0
  env = GDK_DPI_SCALE,1.0
  env = GT_SCALE_FACTOR,1.0

#+end_src

** Hardware acceleration
#+begin_src conf
  env = WLR_RENDERER, vulkan
  env = NVD_BACKEND, direct

#+end_src

** Tearing control (optional)
#+begin_src conf
  env = __GL_SYNC_TO_VBLANK, 1 # 0=off (gaming), 1=on (no tearing)
  env = __GL_SYNC_DISPLAY_DEVICE, $monitor1
  env = __GL_YIELD, USLEEP

#+end_src


* AUTO START
#+begin_src conf
  exec-once = dbus-update-activation-environment --system WAYLAND_DISPLAY DISPLAY
  exec-once = wl-paste --watch cliphist store # Clipboard 
  exec-once = wlr-randr --output DP-6 --adaptive-sync enabled
  exec-once = optimus-manager --set-startup hybrid

#+end_src

** Daemon's
#+begin_src conf
  exec-once = swww-daemon --format xrgb
  exec-once = emacs -daemon

#+end_src

** Packages
#+begin_src conf
  exec-once = waybar
  exec-once = hyprlock
  exec-once = dunst

#+end_src

** NVIDIA power management
#+begin_src conf
  #exec-once = sudo nvidia-smi -pm 1
  #exec-once = sudo systemctl start nvidia-persistenced

#+end_src

** Workspaces
#+begin_src conf
  exec-once = hyprctl dispatch workspace 11
  exec-once = hyprctl dispatch workspace 1

#+end_src


* LOOK AND FEEL
#+begin_src conf
  # Refer to https://wiki.hyprland.org/Configuring/Variables/

  # https://wiki.hyprland.org/Configuring/Variables/#general
  general {
      gaps_in = 5
      gaps_out = 20

      border_size = 2

      # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
      col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
      col.inactive_border = rgba(595959aa)

      # Set to true enable resizing windows by clicking and dragging on borders and gaps
      resize_on_border = false

      # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
      allow_tearing = false

      layout = dwindle
  }

  # https://wiki.hyprland.org/Configuring/Variables/#decoration
  decoration {
      rounding = 5
      rounding_power = 2

      # Change transparency of focused and unfocused windows
      active_opacity = 0.9
      inactive_opacity = 0.6
      
      shadow {
          enabled = true
          range = 4
          render_power = 3
          color = rgba(1a1a1aee)
      }

      # https://wiki.hyprland.org/Configuring/Variables/#blur
      blur {
          enabled = true
          size = 3
          passes = 1
  	ignore_opacity = yes

          vibrancy = 0.1696
      }
  }

  # https://wiki.hyprland.org/Configuring/Variables/#animations
  animations {
      enabled = yes, please :)

      # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

      bezier = easeOutQuint,0.23,1,0.32,1
      bezier = easeInOutCubic,0.65,0.05,0.36,1
      bezier = linear,0,0,1,1
      bezier = almostLinear,0.5,0.5,0.75,1.0
      bezier = quick,0.15,0,0.1,1

      animation = global, 1, 10, default
      animation = border, 1, 5.39, easeOutQuint
      animation = windows, 1, 4.79, easeOutQuint
      animation = windowsIn, 1, 4.1, easeOutQuint, popin 87%
      animation = windowsOut, 1, 1.49, linear, popin 87%
      animation = fadeIn, 1, 1.73, almostLinear
      animation = fadeOut, 1, 1.46, almostLinear
      animation = fade, 1, 3.03, quick
      animation = layers, 1, 3.81, easeOutQuint
      animation = layersIn, 1, 4, easeOutQuint, fade
      animation = layersOut, 1, 1.5, linear, fade
      animation = fadeLayersIn, 1, 1.79, almostLinear
      animation = fadeLayersOut, 1, 1.39, almostLinear
      animation = workspaces, 1, 1.94, almostLinear, fade
      animation = workspacesIn, 1, 1.21, almostLinear, fade
      animation = workspacesOut, 1, 1.94, almostLinear, fade
  }

  # Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
  # "Smart gaps" / "No gaps when only"
  # uncomment all if you wish to use that.
  # workspace = w[tv1], gapsout:0, gapsin:0
  # workspace = f[1], gapsout:0, gapsin:0
  # windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
  # windowrule = rounding 0, floating:0, onworkspace:w[tv1]
  # windowrule = bordersize 0, floating:0, onworkspace:f[1]
  # windowrule = rounding 0, floating:0, onworkspace:f[1]

  # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
  dwindle {
      pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
      preserve_split = true # You probably want this
  }

  # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
  master {
      new_status = master
  }

  # https://wiki.hyprland.org/Configuring/Variables/#misc
  misc {
      vrr = 1
      vfr = on
      disable_autoreload = yes
      
      force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
      disable_hyprland_logo = yes # If true disables the random hyprland logo / anime girl background. :(
      focus_on_activate = yes
      disable_splash_rendering = no
  }

#+end_src


* INPUT
#+begin_src conf
  # https://wiki.hyprland.org/Configuring/Variables/#input
  input {
      kb_layout = pt
      kb_variant =
      kb_model =
      #kb_options =
      #kb_rules =

      follow_mouse = 1
      float_switch_override_focus = 0

      sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

      touchpad {
      	 natural_scroll = true
      }
  }

  # https://wiki.hyprland.org/Configuring/Variables/#gestures
  gestures {
      workspace_swipe = true
  }

#+end_src


* KEYBINDINGS
#+begin_src conf
  # See https://wiki.hyprland.org/Configuring/Keywords/
  $mainMod = SUPER # Sets "Windows" key as main modifier
  
#+end_src

** Main
#+begin_src conf
  # Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
  bind = $mainMod, Q, exec, $terminal
  bind = $mainMod, C, killactive,
  bind = $mainMod, M, exit,
  bind = $mainMod, E, exec, $fileManager
  bind = $mainMod, V, togglefloating,
  bind = $mainMod, R, exec, $menu
  bind = $mainMod, P, pseudo, # dwindle
  bind = $mainMod, J, togglesplit, # dwindle
  bind = $mainMod SHIFT, R, exec, hyprctl reload


#+end_src

** SWWW change random wallpaper
#+begin_src conf
  bind = $mainMod, W, exec, ~/.config/swww/swww.sh; sleep 1.5

#+end_src

** Workspaces
*** Switch workspace
#+begin_src conf
  # Switch workspaces with mainMod + [0-9]
  bind = $mainMod, 1, exec, hyprsome workspace 1
  bind = $mainMod, 2, exec, hyprsome workspace 2
  bind = $mainMod, 3, exec, hyprsome workspace 3
  bind = $mainMod, 4, exec, hyprsome workspace 4
  bind = $mainMod, 5, exec, hyprsome workspace 5
  bind = $mainMod, 6, exec, hyprsome workspace 6
  bind = $mainMod, 7, exec, hyprsome workspace 7
  bind = $mainMod, 8, exec, hyprsome workspace 8
  bind = $mainMod, 9, exec, hyprsome workspace 9

  # Scroll through existing workspaces with mainMod + scroll
  bind = $mainMod CTRL, left, workspace, e-1
  bind = $mainMod CTRL, right, workspace, e+1

#+end_src

*** Move window to workspace
#+begin_src conf
  # Move active window to a workspace with mainMod + SHIFT + [0-9]
  bind = $mainMod SHIFT, 1, exec, hyprsome move 1
  bind = $mainMod SHIFT, 2, exec, hyprsome move 2
  bind = $mainMod SHIFT, 3, exec, hyprsome move 3
  bind = $mainMod SHIFT, 4, exec, hyprsome move 4
  bind = $mainMod SHIFT, 5, exec, hyprsome move 5
  bind = $mainMod SHIFT, 6, exec, hyprsome move 6
  bind = $mainMod SHIFT, 7, exec, hyprsome move 7
  bind = $mainMod SHIFT, 8, exec, hyprsome move 8
  bind = $mainMod SHIFT, 9, exec, hyprsome move 9

  # Move active window with mainMod + scroll
  bind = $mainMod SHIFT, left, movetoworkspace, e-1
  bind = $mainMod SHIFT, right, movetoworkspace, e+1

#+end_src

*** Move between monitors
#+begin_src conf
  bind = $mainMod CTRL, up, focusmonitor, +1
  bind = $mainMod CTRL, down, focusmonitor, -1

#+end_src

*** Window actions
#+begin_src conf
  # Move focus with mainMod + arrow keys
  bind = $mainMod, left, movefocus, l
  bind = $mainMod, right, movefocus, r
  bind = $mainMod, up, movefocus, u
  bind = $mainMod, down, movefocus, d

  # Move/resize windows with mainMod + LMB/RMB and dragging
  bindm = $mainMod, mouse:272, movewindow
  bindm = $mainMod, mouse:273, resizewindow

#+end_src

** Other
#+begin_src conf
  # Laptop multimedia keys for volume and LCD brightness
  bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
  bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
  bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
  bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
  bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
  bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-

  # Requires playerctl
  bindl = , XF86AudioNext, exec, playerctl -p spotify next
  bindl = , XF86AudioPause, exec, playerctl -p spotify play-pause
  bindl = , XF86AudioPlay, exec, playerctl -p spotify play-pause
  bindl = , XF86AudioPrev, exec, playerctl -p spotify previous

  # Screenshots
  bind = $mainMod, S, submap, screenshots
  submap = screenshots

  binde = , W, exec, hyprctl screenshot window
  binde = , M, exec, hyprctl screenshot monitor

  bind = , escape, submap, reset
  submap = reset

#+end_src


* WINDOWS AND WORKSPACES
#+begin_src conf
  # See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
  # See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

  # Example windowrule
  # windowrule = float,class:^(kitty)$,title:^(kitty)$

  # Ignore maximize requests from apps. You'll probably like this.
  windowrule = suppressevent maximize, class:.*

  # Fix some dragging issues with XWayland
  windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

#+end_src


